hs.hotkey.bind({"ctrl", "alt"}, "Left", windowMoveAndResize("Left"))
hs.hotkey.bind({"ctrl", "alt"}, "Right", windowMoveAndResize("Right"))
hs.hotkey.bind({"ctrl", "alt"}, "Up", windowFill)
hs.hotkey.bind({"alt", "cmd"}, "Right", windowGrowWidth)
hs.hotkey.bind({"alt", "cmd"}, "Left", windowShrinkWidth)
hs.hotkey.bind({"alt", "cmd"}, "Up", windowMoveAndResize("Top"))
hs.hotkey.bind({"alt", "cmd"}, "Down", windowMoveAndResize("Bottom"))
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "Right", windowMoveToDisplay(1))
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "Left", windowMoveToDisplay(2))
hs.hotkey.bind({"ctrl", "cmd"}, "d", toggleDarkMode)
hs.hotkey.bind({"ctrl", "shift"}, "d", typeDate)
-- hs.hotkey.bind({"alt"}, "l", systemSleep)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "forwarddelete", systemShutdown)
